name: publish
on: [push]

jobs:
  publish-docker-image:
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            platform: linux/amd64
          - builder: ubuntu-24.04-arm
            platform: linux/arm64

    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Build the Docker image
      #   run: |
      #     docker build . --tag ghcr.io/kayxue/blogbackend:latest --no-cache
      #     docker push ghcr.io/kayxue/blogbackend:latest
      
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/kayxue/githubpushnotificationlinebot:latest